project_id = "zdgpxmtapbviwrpcleqi"

[functions.verify-identity]
verify_jwt = false

[functions.delete-account]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.extract-candidates]
verify_jwt = false

[functions.notify-admin-new-user]
verify_jwt = false

[functions.fetch-candidate-info]
verify_jwt = false

[functions.proxy-image]
verify_jwt = false